name: LPRankCommand
version: ${project.version}
main: me.minhcrafters.lprankcommand.Main
authors: [ MinhCrafters ]
description: Set player's rank. (LuckPerms only!)
depend: [LuckPerms]

commands:
  rank:
    aliases: []